services:
  django:
    build: ./CRAIMAS
    command: gunicorn -b 0.0.0.0:8000 settings.wsgi
    expose:
      - "8000"
    volumes:
      - ./CRAIMAS:/CRAIMAS
    depends_on:
      - postgres


  postgres:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/postgres_backup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  nginx:
    image: nginx:1.27
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./CRAIMAS/staticfiles:/static
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: renew --force-renewal


volumes:
  postgres_data:
  postgres_backup:
