version: "3.8"

services:
  django:
    build: ./CRAIMAS
    command: gunicorn -b 0.0.0.0:8000 settings.wsgi
    expose:
      - "8000"
    volumes:
      - ./CRAIMAS:/CRAIMAS
    depends_on:
      - postgres


  postgres:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  nginx:
    image: nginx:latest
    ports:
      - 800:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./CRAIMAS/staticfiles:/static
      - ./certbot:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - django
    command: "/bin/sh -c 'while :; do sleep 20d & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  certbot:
        image: certbot/certbot:v1.7.0
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt
          - /var/www/html:/var/www/html
        command: ["certonly --webroot -w /var/www/html -d craimas.com"]


volumes:
  postgres_data: