services:
  django:
    build: ./CRAIMAS
    command: uvicorn settings.asgi:application --host 0.0.0.0 --port 8000 --reload
    expose:
      - "8000"
    volumes:
      - ./CRAIMAS:/CRAIMAS
    depends_on:
      - postgres


  postgres:
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_backup:/postgres_backup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  nginx:
    image: nginx:1.27
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./CRAIMAS/staticfiles:/static
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - django
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 61d & wait $${!}; done;'"




volumes:
  postgres_data:
